### PR TITLE
psu: Fix always freeing NULL 

### LINKED ISSUE #735: gcc warning compiling psu
On gcc 13.1.1 there's a new  compilation warning while compiling psu:
```
psu/psu.c: In function ‘parse_byte_string’:
psu/psu.c:376:17: warning: pointer ‘ptr’ may be used after ‘realloc’ [-Wuse-after-free]
  376 |                 free(ptr);
      |                 ^~~~~~~~~
psu/psu.c:374:27: note: call to ‘realloc’ here
  374 |         if (!(blob->ptr = realloc(ptr, str.end - str.ptr + 1 ))) {
  ```
 .
 Target: arma7v9-zynq7000-qemu
 IMO it's a false positive.

### PR DESCRIPTION
**Pull request by agkaminski**
DONE: RTOS-553

## Description

Fixes https://github.com/phoenix-rtos/phoenix-rtos-project/issues/735

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by agkaminski** [comment]
@badochov I have much older gcc, could you confirm that the warning is indeed fixed?

File: psu/psu.c [hunk 1]
```diff
@@ -374,18 +374,21 @@ static inline int8_t char_to_hex(char c)
...
 {
-	void *ptr = blob->ptr;
+	void *ptr;
 	int8_t bh, bl;
 
-	if (!(blob->ptr = realloc(ptr, str.end - str.ptr + 1 ))) {
-		*blob = SCRIPT_BLOB_EMPTY;
+	ptr = realloc(blob->ptr, str.end - str.ptr + 1);
+	if (ptr == NULL) {
 		free(ptr);
```
Comment (anglov) [inline psu/psu.c]: free(blob->ptr)

**Review by badochov — APPROVED** [review]
LGTM, error no longer occurs
